# set LOGSTASH_HOST to dns/ip of logstash host

proxy:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "proxy"

ldap:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "ldap"

gitlab-postgresql:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "gitlab-postgresql"

gitlab:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "gitlab"

gitlab-redis:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "gitlab-redis"

sensu-uchiwa:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sensu-uchiwa"

sensu-api:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sensu-api"

sensu-server:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sensu-server"

sensu-client:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sensu-client"

sensu-rabbitmq:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sensu-rabbitmq"

sensu-redis:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sensu-redis"

sonar-mysql:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sonar-mysql"

sonar:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "sonar"

jenkins:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "jenkins"

jenkins-slave:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "jenkins-slave"

nexus:
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "nexus"
